### PR TITLE
Instantiate Root with an existing redis connection

### PR DESCRIPTION
**Pull request by reubano**
This is more flexible and allows easy heroku integration

```python
redis_url = getenv('REDISTOGO_URL')
conn = redis.from_url(redis_url)
root = Root(conn)
```

### CODE REVIEW

**Comment by LeMinaw** [comment]
This should definitly gets merged.
Very useful, simple, and does not breaks existing code.

**Comment by LeMinaw** [comment]
Actually, you can already pass an argument called 'redis' to __init__.

**Comment by seperman** [comment]
Hi @reubano 
Thanks for the PR. Sorry it took me so long to merge it. I am trying to find some free time to fix some issues of this package.

**Comment by reubano** [comment]
Fixes #2

**Pull request merged**
